# Generated by Django 5.2 on 2025-05-25 14:25

import django.db.models.deletion
import vehicles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20)),
                ('plate_image', models.ImageField(blank=True, null=True, upload_to=vehicles.models.plate_image_upload_path)),
                ('registration_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'vehicle_name'), name='unique_vehicle_name_per_user'), models.UniqueConstraint(fields=('user', 'model'), name='unique_model_per_user'), models.UniqueConstraint(fields=('user', 'plate_number'), name='unique_plate_per_user')],
            },
        ),
    ]
